slice_name: "comm-08 \xB7 \u0421\u0442\u0440\u0443\u043A\u0442\u0443\u0440\u0430 \u0441\
  \u0435\u0431\u0435\u0441\u0442\u043E\u0438\u043C\u043E\u0441\u0442\u0438 \u043F\u043E\
  \ \u0442\u043E\u0432\u0430\u0440\u0430\u043C"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  viz_type: echarts_timeseries_bar
  metrics:
  - mat_main_sum
  - mat_aux_sum
  - sewing_sum
  - cutting_sum
  - decor_sum
  - knitting_sum
  - other_sum
  x_axis: model_name
  x_axis_sort_series_type: name
  x_axis_sort_series_ascending: true
  time_grain_sqla: null
  granularity_sqla: null
  row_limit: 20
  stack: Stack
  y_axis_title: BYN
  y_axis_format: ',.0f'
  legend_orientation: right
  orientation: vertical
query_context: null
cache_timeout: null
uuid: 172a9c5e-68b8-449e-a2e8-84f46f4e200d
version: 1.0.0
dataset_uuid: c7619b95-6ed8-428a-9c73-fc7ad310d71d
