slice_name: "comm-07 \xB7 \u0414\u0438\u043D\u0430\u043C\u0438\u043A\u0430 \u0446\u0435\
  \u043D \u043F\u043E \u043C\u0435\u0441\u044F\u0446\u0430\u043C \u0432\u044B\u043F\
  \u0443\u0441\u043A\u0430"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 4__table
  viz_type: echarts_timeseries_line
  metrics:
  - "\u0421\u0435\u0431\u0435\u0441\u0442\u043E\u0438\u043C\u043E\u0441\u0442\u044C"
  - "\u041E\u0442\u043F\u0443\u0441\u043A\u043D\u0430\u044F"
  - "\u0420\u043E\u0437\u043D\u0438\u0447\u043D\u0430\u044F"
  x_axis: prod_ym_label
  row_limit: 1000
  y_axis_title: ''
  y_axis_format: ',.2f'
  markerEnabled: true
  groupby: []
  timeseries_limit_metric: ym_sort
  x_axis_sort: ym_sort
  x_axis_sort_asc: true
  order_desc: false
  sort_series_type: sum
  sort_series_ascending: true
  seriesType: smooth
  markerSize: 5
  rich_tooltip: true
  show_legend: true
  legendOrientation: bottom
  legendType: plain
  truncateYAxis: false
  currency_format:
    symbol: AUTO
    symbolPosition: suffix
  showTooltipTotal: false
  showTooltipPercentage: false
query_context: null
cache_timeout: null
uuid: 7e7fe92b-8ddd-4dbe-a190-29adaab659dd
version: 1.0.0
dataset_uuid: c7619b95-6ed8-428a-9c73-fc7ad310d71d
