slice_name: "cost-stage-fullchain \xB7 \u041C\u043E\u0434\u0435\u043B\u0438 \u0441\
  \u043E \u0432\u0441\u0435\u043C\u0438 4 \u044D\u0442\u0430\u043F\u0430\u043C\u0438"
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  viz_type: table
  all_columns:
  - model
  - articul
  - stage_order
  - stage_label
  - cost_byn
  - price_byn
  - calc_date
  - level01
  - brand_manager
  columns:
  - model
  - articul
  - stage_order
  - stage_label
  - cost_byn
  - price_byn
  - calc_date
  - level01
  - brand_manager
  query_mode: raw
  include_time: false
  order_desc: true
  adhoc_filters:
  - clause: WHERE
    expressionType: SIMPLE
    subject: stages_present
    operator: ==
    comparator: 4
  row_limit: 200
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"stages_present","op":"==","val":4}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["model","articul","stage_order","stage_label","cost_byn","price_byn","calc_date","level01","brand_manager"],"orderby":[],"annotation_layers":[],"row_limit":200,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":4,"expressionType":"SIMPLE","operator":"==","subject":"stages_present"}],"all_columns":["model","articul","stage_order","stage_label","cost_byn","price_byn","calc_date","level01","brand_manager"],"columns":["model","articul","stage_order","stage_label","cost_byn","price_byn","calc_date","level01","brand_manager"],"datasource":"1__table","include_time":false,"order_desc":true,"query_mode":"raw","row_limit":200,"slice_id":3,"viz_type":"table","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7891df3c-da30-489d-ad8d-f26f8693421f
version: 1.0.0
dataset_uuid: 882f62e1-e76b-4c69-afd3-4b138a7d9a23
