slice_name: "cost-stage-median \xB7 \u0421\u0435\u0431\u0435\u0441\u0442\u043E\u0438\
  \u043C\u043E\u0441\u0442\u044C \u043F\u043E \u044D\u0442\u0430\u043F\u0430\u043C\
  \ \u043A\u0430\u043B\u044C\u043A\u0443\u043B\u0438\u0440\u043E\u0432\u0430\u043D\
  \u0438\u044F (\u043C\u0435\u0434\u0438\u0430\u043D\u0430, BYN)"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  viz_type: echarts_timeseries_bar
  metrics:
  - aggregate: MAX
    column:
      column_name: cost_median
    expressionType: SIMPLE
    label: "\u041C\u0435\u0434\u0438\u0430\u043D\u043D\u0430\u044F \u0441\u0435\u0431\
      \u0435\u0441\u0442\u043E\u0438\u043C\u043E\u0441\u0442\u044C, BYN"
    optionName: metric_cost_median
    sqlExpression: null
    hasCustomLabel: true
    datasourceWarning: false
  x_axis: stage_label
  x_axis_sort_series_type: name
  x_axis_sort_series_ascending: true
  time_grain_sqla: null
  granularity_sqla: null
  row_limit: 100
  y_axis_title: BYN
  y_axis_format: ',.2f'
  show_legend: false
  legend_orientation: right
  orientation: vertical
query_context: "{\"datasource\":{\"id\":2,\"type\":\"table\"},\"force\":false,\"queries\"\
  :[{\"granularity\":null,\"filters\":[],\"extras\":{\"time_grain_sqla\":null,\"having\"\
  :\"\",\"where\":\"\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":null,\"\
  columnType\":\"BASE_AXIS\",\"sqlExpression\":\"stage_label\",\"label\":\"stage_label\"\
  ,\"expressionType\":\"SQL\",\"isColumnReference\":true}],\"metrics\":[{\"aggregate\"\
  :\"MAX\",\"column\":{\"column_name\":\"cost_median\"},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"label\":\"\u041C\u0435\u0434\
  \u0438\u0430\u043D\u043D\u0430\u044F \u0441\u0435\u0431\u0435\u0441\u0442\u043E\u0438\
  \u043C\u043E\u0441\u0442\u044C, BYN\",\"optionName\":\"metric_cost_median\",\"sqlExpression\"\
  :null}],\"orderby\":[[{\"aggregate\":\"MAX\",\"column\":{\"column_name\":\"cost_median\"\
  },\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"\
  label\":\"\u041C\u0435\u0434\u0438\u0430\u043D\u043D\u0430\u044F \u0441\u0435\u0431\
  \u0435\u0441\u0442\u043E\u0438\u043C\u043E\u0441\u0442\u044C, BYN\",\"optionName\"\
  :\"metric_cost_median\",\"sqlExpression\":null},false]],\"annotation_layers\":[],\"\
  row_limit\":100,\"series_limit\":0,\"group_others_when_limit_reached\":false,\"\
  order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\":{},\"\
  time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\":{\"\
  index\":[\"stage_label\"],\"columns\":[],\"aggregates\":{\"\u041C\u0435\u0434\u0438\
  \u0430\u043D\u043D\u0430\u044F \u0441\u0435\u0431\u0435\u0441\u0442\u043E\u0438\u043C\
  \u043E\u0441\u0442\u044C, BYN\":{\"operator\":\"mean\"}},\"drop_missing_columns\"\
  :true}},{\"operation\":\"flatten\"}]}],\"form_data\":{\"datasource\":\"2__table\"\
  ,\"granularity_sqla\":null,\"legend_orientation\":\"right\",\"metrics\":[{\"aggregate\"\
  :\"MAX\",\"column\":{\"column_name\":\"cost_median\"},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":true,\"label\":\"\u041C\u0435\u0434\
  \u0438\u0430\u043D\u043D\u0430\u044F \u0441\u0435\u0431\u0435\u0441\u0442\u043E\u0438\
  \u043C\u043E\u0441\u0442\u044C, BYN\",\"optionName\":\"metric_cost_median\",\"sqlExpression\"\
  :null}],\"orientation\":\"vertical\",\"row_limit\":100,\"show_legend\":false,\"\
  slice_id\":1,\"time_grain_sqla\":null,\"viz_type\":\"echarts_timeseries_bar\",\"\
  x_axis\":\"stage_label\",\"x_axis_sort_series_ascending\":true,\"x_axis_sort_series_type\"\
  :\"name\",\"y_axis_format\":\",.2f\",\"y_axis_title\":\"BYN\",\"force\":false,\"\
  result_format\":\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"\
  result_type\":\"full\"}"
cache_timeout: null
uuid: d1e0b2bf-6149-44e7-a6aa-b64d16429332
version: 1.0.0
dataset_uuid: 3150bca1-2ac4-4e84-aeb2-1b2195e542b1
