slice_name: "marg-08 \xB7 \u0414\u0438\u043D\u0430\u043C\u0438\u043A\u0430 \u043C\u0430\
  \u0440\u0436\u0438 \u0432\u044B\u043F\u0443\u0441\u043A\u0430"
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 14__table
  viz_type: mixed_timeseries
  x_axis: prod_month
  time_grain_sqla: P1M
  metrics:
  - margin_cur
  - margin_py
  groupby: []
  adhoc_filters: []
  row_limit: 1000
  metrics_b:
  - growth_py_pct
  groupby_b: []
  adhoc_filters_b: []
  row_limit_b: 1000
  seriesType: bar
  seriesTypeB: line
  yAxisIndex: 0
  yAxisIndexB: 1
  y_axis_format: ',.0f'
  y_axis_format_secondary: +,.1f
  y_axis_title: ''
  y_axis_title_secondary: '%'
  x_axis_time_format: '%m.%Y'
  show_legend: true
  legend_orientation: bottom
  markerEnabledB: true
  markerSizeB: 5
  rich_tooltip: true
  truncateYAxis: true
  truncate_metric: true
  color_scheme: supersetColors
  extra_form_data: {}
query_context: null
cache_timeout: null
uuid: 2a603148-bf9f-4c29-9230-ac5a44576651
version: 1.0.0
dataset_uuid: 5f8d39fb-957e-4b5d-8b00-60a66a6f37c2
